### ISSUE TITLE
RegisterCallback registration dies if aset dies

### ISSUE THREAD

**Issue by haraldsteinlechner** [vrvis/aardvark#11]
According to our mental model, callbacks should never die unless disposed. 

Registering a callback, out-of-scoping the source set results in a immediately dying callback function. Note that this only works if the creation of the stuff in a separate function.
see 9e2dd80ddccf92bf2ec3ab615e71a1df65c62f9c

There is the weak table from something like set -> callback but there is no strong holder on set or readers as far as i can tell

**Comment by krauthaufen** [comment]
that behaviour was artificially introduced (said WeakTable) since no one ever uses subscriptions cleanly...

In fact changing that would break most projects and require users to manage their subscriptions manually.

I would personally rename the current registerCallback to registerCallbackIAmNeverGonnaDisposeThisSubscription or some crazy name like that and introduce a new one having the clean semantics....

**Comment by haraldsteinlechner** [comment]
Behaviour should be exactly as is. 
In Rx the input forces the existence of all outputs including callbacks because callbacks and mutation are only supermechanism for everything.
In our system, an out of scope output cannot be queried and thus the callbacks cannot be triggered in a lazy world. 
Callbacks however break laziness and therefore should force the whole graph to be alive.
Still, our current implementation is more powerful, by simply keeping the disposable alive artifically.

As a result i agree with your proposal to introduce registerCallbackIAmNeverGonnaDisposeThisSubscription additionally to the current one.

**Comment by haraldsteinlechner** [comment]
fixed in dee6b3ec9ba6accbd144ec58038e63c5ad017f55
